telegram:
  api_id: 25467884
  api_hash: "05a687da36243593d4eb624f46375341"
  token: "6237395262:AAEzrtlq-OT4KfZpaXpwl7T9r69DxILyU2c"
  lang_code: !!str "en"
  max_upload_tasks: 5
  url_validation_regexes:
    - "^http(s)?:\\/\\/.+$"
  allowed_users:
    - id: 2139560486
      send_startup_message: !!bool True
      download_media_type: !!str "VIDEO"
      save_to_storage: !!bool False
      use_url_regex_match: !!bool True
      upload:
        upload_video_file: !!bool True
        upload_video_max_file_size: 2147483648
        forward_to_group: !!bool False
        forward_group_id: -1001931198481
        silent: !!bool False
        video_caption:
          include_title: !!bool True
          include_filename: !!bool False
          include_link: !!bool True
          include_size: !!bool True
  api:
    upload_video_file: !!bool True
    upload_video_max_file_size: 2147483648
    upload_to_chat_ids:
      -1001931198481
      - -00000000000
    silent: !!bool False
    video_caption:
      include_title: !!bool True
      include_filename: !!bool False
      include_link: !!bool True
      include_size: !!bool True
ytdlp:
  version_check_enabled: !!bool True
  version_check_interval: 86400
  notify_users_on_new_version: !!bool True
